{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "dbapi-sepaInstantCreditTransfer",
    "description" : "Easily initiate SEPA Instant Credit Transfers, both single and bulk, with complementary operations such as status checks, cancellation, second factor retry and payee verification.",
    "termsOfService" : "https://developer.db.com/termsandconditions",
    "contact" : {
      "url" : "https://developer.db.com/contact",
      "email" : "bank.api@db.com"
    },
    "version" : "v3"
  },
  "servers" : [ {
    "url" : "https://simulator-api.db.com:443/gw/dbapi/paymentInitiation/payments/v3"
  } ],
  "tags" : [ {
    "name" : "Create SEPA Instant Credit Transfers",
    "description" : "Use these endpoints to create SEPA Instant Credit Transfers. Both single and bulk payments are supported."
  }, {
    "name" : "Get status for SEPA Instant Credit Transfers",
    "description" : "Use these endpoints to retrieve the processing status of SEPA Instant Credit Transfers, both for single and bulk payments."
  }, {
    "name" : "Get details for SEPA Instant Credit Transfers",
    "description" : "Use these endpoints to retrieve the details of SEPA Instant Credit Transfers, both for single and bulk payments."
  }, {
    "name" : "Reachability Status",
    "description" : "Verifies if the provided IBAN is reachable for an SEPA Instant Credit Transfer"
  }, {
    "name" : "Cancel SEPA Instant Credit Transfers",
    "description" : "Use these endpoints to cancel existing SEPA Instant Credit Transfers."
  }, {
    "name" : "Second Factor Retry",
    "description" : "Use these endpoints for Second Factory Retry of existing SEPA Instant Credit Transfers."
  }, {
    "name" : "Get VoP details for SEPA Instant Credit Transfers",
    "description" : "Use these endpoints to check the Verification of Payee (VoP) details for your SEPA Instant Credit Transfers, whether you're making a single payment or a bulk transfer. "
  } ],
  "paths" : {
    "/sepaInstantCreditTransfer" : {
      "post" : {
        "tags" : [ "Create SEPA Instant Credit Transfers" ],
        "summary" : "Initiate a SEPA Instant Credit Transfer",
        "description" : "Initiate a SEPA Instant Credit Transfer from your own or customer's account to another SEPA account. The transaction(s) must be approved within five minutes. Strong Customer Authentication (SCA) is required prior to the final execution of the payment. Should the second factor authentication fail, it may be retried for the same paymentId using the Second Factor Retry endpoint, without the need to re-initiate the payment, provided the five-minute time window has not elapse[...]",
        "operationId" : "performPaymentInstant",
        "security" : [ {
          "api_auth_code" : [ "instant_sepa_credit_transfers" ]
        }, {
          "api_db_smart_access" : [ "instant_sepa_credit_transfers" ]
        } ]
      }
    },
    "/sepaInstantCreditTransfer/{paymentId}/status" : {
      "get" : {
        "tags" : [ "Get status for SEPA Instant Credit Transfers" ],
        "summary" : "Retrieve the status of the SEPA Instant Credit Transfer",
        "description" : "Retrieve the status of a previously initiated SEPA Instant Credit Transfer.",
        "operationId" : "getPaymentStatus",
        "security" : [ {
          "api_auth_code" : [ "instant_sepa_credit_transfers" ]
        }, {
          "api_db_smart_access" : [ "instant_sepa_credit_transfers" ]
        } ]
      }
    },
    "/sepaInstantCreditTransfer/{paymentId}" : {
      "get" : {
        "tags" : [ "Get details for SEPA Instant Credit Transfers" ],
        "summary" : "Retrieve the details of the SEPA Instant Credit Transfer",
        "description" : "Retrieve the details of a previously initiated SEPA Instant Credit Transfer.",
        "security" : [ {
          "api_auth_code" : [ "instant_sepa_credit_transfers" ]
        }, {
          "api_db_smart_access" : [ "instant_sepa_credit_transfers" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Cancel SEPA Instant Credit Transfers" ],
        "summary" : "Cancel the SEPA Instant Credit Transfers",
        "description" : "Cancel a previously initiated SEPA Instant Credit Transfer.",
        "security" : [ {
          "api_auth_code" : [ "instant_sepa_credit_transfers" ]
        }, {
          "api_db_smart_access" : [ "instant_sepa_credit_transfers" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Second Factor Retry" ],
        "summary" : "Second factor retry for SEPA Credit Transfers",
        "description" : "Retry the second factor authentication for an existing payment in case it fails. A new second factor attempt can be made for the same paymentId without re-initiating the payment.",
        "security" : [ {
          "api_auth_code" : [ "instant_sepa_credit_transfers" ]
        }, {
          "api_db_smart_access" : [ "instant_sepa_credit_transfers" ]
        } ]
      }
    },
    "/sepaInstantCreditTransfer/{paymentId}/vopDetails" : {
      "get" : {
        "tags" : [ "Get VoP details for SEPA Instant Credit Transfers" ],
        "summary" : "Retrieve the VoP details for a single SEPA Instant Credit Transfer",
        "description" : "Retrieve the Verification of Payee (VoP) details for a single SEPA Instant Credit Transfer. This endpoint confirms whether the beneficiary's name matches the provided IBAN before payment execution. It can be called if the payment initiation did not return a final VoP response and the status is TRY_AGAIN.",
        "security" : [ {
          "api_auth_code" : [ "instant_sepa_credit_transfers" ]
        }, {
          "api_db_smart_access" : [ "instant_sepa_credit_transfers" ]
        } ]
      }
    },
    "/sepaInstantCreditTransfer/bulk/{paymentId}/vopDetails" : {
      "get" : {
        "tags" : [ "Get VoP details for SEPA Instant Credit Transfers" ],
        "summary" : "Retrieve the VoP details for Bulk SEPA Instant Credit Transfers",
        "description" : "Retrieve the Verification of Payee (VoP) details for Bulk SEPA Instant Credit Transfers. This endpoint confirms whether the beneficiary's name matches the provided IBAN before payment execution. It can be called if the payment initiation did not return a final VoP response and the status is TRY_AGAIN.",
        "security" : [ {
          "api_auth_code" : [ "bulk_instant_sepa_credit_transfers" ]
        }, {
          "api_db_smart_access" : [ "bulk_instant_sepa_credit_transfers" ]
        } ]
      }
    },
    "/creditorAccounts/{iban}/reachabilityStatus" : {
      "get" : {
        "tags" : [ "Reachability Status" ],
        "summary" : "Verifies if the provided IBAN is reachable for an SEPA Instant Credit Transfer.",
        "description" : "Verifies if the provided IBAN is reachable for an SEPA Instant Credit Transfer.",
        "operationId" : "getReachabilityStatus",
        "security" : [ {
          "api_auth_code" : [ "instant_sepa_credit_transfers" ]
        }, {
          "api_db_smart_access" : [ "instant_sepa_credit_transfers" ]
        } ]
      }
    },
    "/sepaInstantCreditTransfer/bulk" : {
      "post" : {
        "tags" : [ "Create SEPA Instant Credit Transfers" ],
        "summary" : "Initiate Bulk SEPA Instant Credit Transfers",
        "description" : "Initiate Bulk SEPA Instant Credit Transfers from your own or your customer’s account to other SEPA accounts. The transaction(s) must be approved within five minutes. Strong Customer Authentication (SCA) is required prior to the final execution of the payment. Should the second factor authentication fail, it may be retried for the same paymentId using the Second Factor Retry endpoint, without the need to re-initiate the payment, provided the five-minute time window has no[...]",
        "security" : [ {
          "api_auth_code" : [ "bulk_instant_sepa_credit_transfers" ]
        }, {
          "api_db_smart_access" : [ "bulk_instant_sepa_credit_transfers" ]
        } ]
      }
    },
    "/sepaInstantCreditTransfer/bulk/{paymentId}/status" : {
      "get" : {
        "tags" : [ "Get status for SEPA Instant Credit Transfers" ],
        "summary" : "Retrieve the status of the Bulk SEPA Instant Credit Transfers",
        "description" : "Returns the status of a previously initiated Bulk SEPA Instant Credit Transfer.",
        "security" : [ {
          "api_auth_code" : [ "bulk_instant_sepa_credit_transfers" ]
        }, {
          "api_db_smart_access" : [ "bulk_instant_sepa_credit_transfers" ]
        } ]
      }
    },
    "/sepaInstantCreditTransfer/bulk/{paymentId}" : {
      "get" : {
        "tags" : [ "Get details for SEPA Instant Credit Transfers" ],
        "summary" : "Retrieve the details of the Bulk SEPA Instant Credit Transfers",
        "description" : "Retrieve the details of a previously initiated Bulk SEPA Instant Credit Transfer.",
        "security" : [ {
          "api_auth_code" : [ "bulk_instant_sepa_credit_transfers" ]
        }, {
          "api_db_smart_access" : [ "bulk_instant_sepa_credit_transfers" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Cancel SEPA Instant Credit Transfers" ],
        "summary" : "Cancel the Bulk SEPA Instant Credit Transfers",
        "description" : "Cancel a previously initiated Bulk SEPA Instant Credit Transfer.",
        "security" : [ {
          "api_auth_code" : [ "bulk_instant_sepa_credit_transfers" ]
        }, {
          "api_db_smart_access" : [ "bulk_instant_sepa_credit_transfers" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Second Factor Retry" ],
        "summary" : "Second factor retry for SEPA Instant Credit Transfers",
        "description" : "Retry the second factor authentication for an existing payment in case it fails. A new second factor attempt can be made for the same paymentId without re-initiating the payment.",
        "security" : [ {
          "api_auth_code" : [ "bulk_instant_sepa_credit_transfers" ]
        }, {
          "api_db_smart_access" : [ "bulk_instant_sepa_credit_transfers" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "api_auth_code" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://simulator-api.db.com:443/gw/oidc/oauth2/authorize",
            "tokenUrl" : "https://simulator-api.db.com:443/gw/oidc/oauth2/token",
            "scopes" : {
              "instant_sepa_credit_transfers" : "Initiate and check status of Instant SEPA Credit Transfers",
              "bulk_instant_sepa_credit_transfers" : "Initiate and check status of Bulk Instant SEPA Credit Transfers",
              "openid" : "Request access to OpenId Connect functionality",
              "offline_access" : "Request an OAuth2 Refresh Token"
            }
          }
        }
      },
      "api_db_smart_access" : {
        "type" : "oauth2",
        "flows" : {
          "clientCredentials" : {
            "tokenUrl" : "https://simulator-api.db.com:443/gw/oidc/oauth2/token",
            "scopes" : {
              "instant_sepa_credit_transfers" : "Initiate and check status of Instant SEPA Credit Transfers",
              "bulk_instant_sepa_credit_transfers" : "Initiate and check status of Bulk Instant SEPA Credit Transfers"
            }
          }
        }
      }
    }
  },
  "x-original-swagger-version" : "2.0"
}